---
title: "ishratc_OriginalHomeworkCode_03"
author: "Ishrat Chowdhury"
date: "October 3, 2019"
output: html_document
---

First let's load our data into R

```{r}
library(curl)
f <- curl("https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN597_Fall19/zombies.csv")
d <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(d)
```

1. Calculate the population mean and standard deviation for each quantitative random variable.

```{r}
height<-d$height
hm<-mean(height)
hm
hsd<-sd(height)
hsd

weight<-d$weight
wm<-mean(weight)
wm
wsd<-sd(weight)
wsd

age<-d$age
am<-mean(age)
am
asd<-sd(age)
asd

zombies_killed<-d$zombies_killed
zm<-mean(zombies_killed)
zm
zsd<-sd(zombies_killed)
zsd

yrs_edu<-d$years_of_education
str(yrs_edu)
ym<-mean(yrs_edu)
ym
ysd<-sd(yrs_edu)
ysd

```

2. Use {ggplot} to make boxplots of each of these variables by gender.

```{r}
mh<- d$height[d$gender == "Male"]
fh<- d$height[d$gender == "Female"]
mw<- d$weight[d$gender == "Male"]
fw<- d$weight[d$gender == "Female"]
ma<- d$age[d$gender == "Male"]
fa<- d$age[d$gender == "Female"]
mz<- d$zombies_killed[d$gender == "Male"]
fz<- d$zombies_killed[d$gender == "Female"]
my<- yrs_edu[d$gender == "Male"]
fy<- yrs_edu[d$gender == "Female"]
par(mfrow =c(1,2))
boxplot(mh, main = "Height", xlab = "Males", ylab = "inches")
boxplot(fh, main = "Height", xlab = "Females", ylab = "inches")
boxplot(mw, main = "Weight", xlab = "Males", ylab = "pounds")
boxplot(fw, main = "Weight", xlab = "Females", ylab = "pounds")
boxplot(ma, main = "Age", xlab = "Males", ylab = "years")
boxplot(fa, main = "Age", xlab = "Females", ylab = "years")
boxplot(mz, main = "# of Zombies Killed", xlab = "Males")
boxplot(fz, main = "# of Zombies Killed", xlab = "Females")
boxplot(my, main = "Years of Education", xlab = "Males", ylab = "years")
boxplot(fy, main = "Years of Education", xlab = "Females", ylab = "years")
```

I'm an idiot it didnt use ggplot
```{r}
library(ggplot2)
height<-as.data.frame(height)
h<- ggplot(height, aes(y=height))+geom_boxplot()
h

```


3. Use {ggplot} to make scatterplots of height and weight un relation to age. Are these variables related? Why?


